DEFAULT: &common
  LOGGING: True
  LOG_DIRECTORY: logs
  LOG_FILE: 'status.log'
  SECRET_KEY: 'cf875e6a24f845e29a824b5de962981d'
  HOST: localhost
  PORT: 4000
  DEBUG: True
  #SERVER_NAME: localhost
  JSONIFY_PRETTYPRINT_REGULAR: true
  REDIS_URL: 'redis://redis:6379'
  STATUS_JSON: 'web/static/json/status.json'
  TRAJECTORY_DIR: 'web/static/json/trajectories/'
  PROFILE_PLOT_DIR: 'web/static/profiles/'
  ERDDAP_URL: 'https://gliders.ioos.us/erddap/tabledap/allDatasets.json'
  DAC_API: 'https://gliders.ioos.us/providers/api/deployment'
  FILE_DIR: '/data/data/priv_erddap/'
  GLIDER_EMAIL:
    EMAIL_ACCOUNT: "xxxxxxxxxxxxxxxxxxxxxxxxx"
    EMAIL_PASSWORD: "xxxxxxxxxxxxxxxxxxxxxxxxx"
    EMAIL_FOLDER: "xxxxxxxxxxxxxxxxxxxxxxxxx"
    OUTPUT_DIRECTORY: 'navo/cache'
  AWS:
    SQS_QUEUE_URL: "xxxxxxxxxxxxxxxxxxxxxxxxx"
    ACCESS_KEY_ID: "xxxxxxxxxxxxxxxxxxxxxxxxx"
    SECRET_ACCESS_KEY: "xxxxxxxxxxxxxxxxxxxxxxxxx"
    REGION_NAME: "xxxxxxxxxxxxxxxxxxxxxxxxx"

DEVELOPMENT: &development
  <<: *common

PRODUCTION: &production
  <<: *common
  DEBUG: False

